# Generated by Django 3.2.5 on 2021-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_shop',
            field=models.BooleanField(default=False, verbose_name='shop'),
        ),
    ]
