# Generated by Django 3.2.5 on 2021-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210919_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
