# Generated by Django 3.2.5 on 2021-09-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_received_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='made_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received_on',
        ),
    ]
