# Generated by Django 3.2.5 on 2021-10-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211005_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
