# Generated by Django 3.2.5 on 2021-09-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210919_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transport',
        ),
    ]
