# Generated by Django 3.2.5 on 2021-09-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210912_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
