# Generated by Django 3.2.5 on 2021-09-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_shop_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(blank=True, upload_to='shop_logos'),
        ),
        migrations.DeleteModel(
            name='ShopImages',
        ),
    ]
