# Generated by Django 3.2.5 on 2021-09-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210912_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_logo',
        ),
    ]
